# region copyright
# Copyright 2023 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

- name: Make sure wallpaper dir exists
  file:
    path: /home/{{ ansible_user }}/Pictures
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Upload wallpaper
  copy:
    src: wallpaper.jpg
    dest: /home/{{ ansible_user }}/Pictures/wallpaper.jpg
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Set wallpaper
  shell: gsettings set org.gnome.desktop.background {{ item }} file:///home/{{ ansible_user }}/Pictures/wallpaper.jpg
  become_user: "{{ ansible_user }}"
  with_items:
    - picture-uri
    - picture-uri-dark
